---
- name: Set cluster to kubeconfig for kubelet.
  shell: |
    "{{ __local_kube_client_binary_root }}/kubectl" config set-cluster "{{ __kube_cluster_name }}" --certificate-authority="{{ __local_kube_ca }}" --embed-certs --server="{{ __apiserver_ha_endpoint }}" --kubeconfig="{{ __local_kube_client_binary_root }}/kubeconfig.kubelet";
    "{{ __local_kube_client_binary_root }}/kubectl" config set-credentials "system:node:{{ kubelet_username }}" --client-certificate="{{ __local_kubelet_client }}" --client-key="{{ __local_kubelet_client_key }}" --embed-certs=true --token={{ __kubelet_user_token }} --kubeconfig="{{ __local_kube_client_binary_root }}/kubeconfig.kubelet"
    "{{ __local_kube_client_binary_root }}/kubectl" config set-context main-cluster-context --cluster="{{ __kube_cluster_name }}" --user="system:node:{{ kubelet_username }}" --kubeconfig="{{ __local_kube_client_binary_root }}/kubeconfig.kubelet"
    "{{ __local_kube_client_binary_root }}/kubectl" config use-context main-cluster-context --kubeconfig="{{ __local_kube_client_binary_root }}/kubeconfig.kubelet"


