#
#   @Description:
#       Generate certificates for Docker Registry 
#
#   @vars:
#       pki_root                Root path of PKI dictionary.
#       registry_cert_root      Root path of Certificates
#       registry_domain         Domain to issue.
#       acme_email              Email of ACME Account.
#

---
- set_fact:
    registry_cert_root: "{{ pki_root }}/registry"
    acme_root: "{{ pki_root }}/acme"

- set_fact:
    registry_token_key: "{{ registry_cert_root }}/token.key"
    registry_token_csr: "{{ registry_cert_root }}/token.csr"
    registry_token_crt: "{{ registry_cert_root }}/token.crt"
    
#- name: Ensure registry domain certificates.
#  include_tasks: roles/certs/tasks/letsencrypt.yml
#  vars:
#    cert_root: "{{ registry_cert_root }}"
#    issue_domain: "{{ registry_domain }}"

- name: Generate token certificate.
  include_tasks: roles/certs/tasks/ca.yml
  vars:
    key_path: "{{ registry_token_key }}"
    csr_path: "{{ registry_token_csr }}"
    crt_path: "{{ registry_token_crt }}"
    issuer:
        CN: Registry Token Certifiate.
        O: StarStudio
