#
#   Deploy and setup kubelet.
#
---
- include_tasks: roles/common/tasks/deploy_bin.yml
  vars:
    src: "{{ __local_kube_client_binary_root }}/kubelet"
    dest: "/usr/bin/kubelet"
    owner: root
    group: root
    mode: 0755

- template:
    src: kubelet.service.j2
    dest: "/usr/lib/systemd/system/kubelet.service"
  register: template_svc_systemd

- template:
    src: kubelet.j2
    dest: "{{ __kubelet_systemd_config_root }}/kubelet"
  register: template_env_kubelet

- template:
    src: config.j2
    dest: "{{ __kubelet_systemd_config_root }}/config"
  register: template_env_kube

- copy:
    src: "{{ __local_kube_client_binary_root }}/kubeconfig.kubelet"
    dest: "{{ __kubelet_config_root }}/kubeconfig"
    owner: root
    group: root
    mode: 0644
  register: kubeconfig_kubelet

- file:
    path: "{{ __kubelet_data_root }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Enable kubelet.
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes

- name: Stop Kubelet.
  service:
    name: kubelet
    state: stopped
  when: template_svc_systemd.changed or template_env_kubelet.changed or template_env_kube.changed or kubeconfig_kubelet.changed

- name: Start kubelet.
  service:
    name: kubelet
    state: started
