---
- set_fact:
      port: "{{ port | default('8098') }}"
      mode: "{{ mode | default('local') }}"
      protocol: "{{ protocol | default('tcp_and_udp') }}"

- name: Ensure Shadowsocks config path exists.
  file:
      path: "{{ data_root }}"
      owner: root
      group: root
      mode: 0755
      state: directory

- name: Generate configure file
  template:
      src: config.json.j2
      dest: "{{ data_root }}/config.json"
      owner: root
      group: root
      mode: 0644
  notify:
    - Compose down
    - Compose

- name: Generate docker-compose file
  template:
      src: docker-compose.yml.j2
      dest: "{{ data_root }}/docker-compose.yml"
  notify:
    - Compose down
    - Compose
