---
- name: Deploy single etcd node.
  hosts: etcd_single
  become_user: "root"
  become: yes

  vars: 
      pki_root: "{{ data_root }}/tls"
      etcd_storage_root:  "{{ data_root }}/etcd/data"

  roles:
    - docker_engine
    - etcd_certs
    - etcd_single
