---
- hosts: servers
  name: Set up GFW-free network environment.
  become: true
  become_user: root

  roles:
    - docker_engine
    - role: cleandns_service
      data_root: "{{ deploy_root }}/cleandns"

    - role: shadowsocks_libev
      data_root: "{{ deploy_root }}/redir"
      mode: redir
      protocol: udp_and_tcp
      port: "{{ redir_port | default('5355') }}"

    #- role: gfw_bypass_redir
    #  state: present
