---
- hosts: dummy
  connection: local

  roles:
    - etcd_certs
    - kube_binaries
    - kube_certs
    - kube_config

#- hosts: all
#  become: yes
#  become_user: root
#
#  roles:
#    - precheck
