---
- name: Compose down
  docker_service:
      project_src: "{{ data_root }}"
      state: absent
      remove_images: all

- name: Compose
  docker_service:
      project_src: "{{ data_root }}"
      state: present 

