#
#   Ensure Kubelet binaries are in required version.
#
#   @params
#       data_root     Path to store necessary data(binaries, configure, etc) during deployment.
#
---

- name: Download binaries requirements.
  get_url:
    url: "{{ item.from }}"
    dest: "{{ item.to }}"
  with_items:
    - from: "{{ kubectl_bin_url }}"
      to: "{{ __local_kube_client_binary_root }}/kubectl"
    - from: "{{ kubelet_bin_url }}"
      to: "{{ __local_kube_client_binary_root }}/kubelet"

- name: Set binaries executable.
  file:
    path: "{{ item }}"
    mode: 0755
  with_items:
    - "{{ __local_kube_client_binary_root }}/kubectl"
    - "{{ __local_kube_client_binary_root }}/kubelet"
