#
#   Download necessary binaries
#
#   @params
#       kube_version                    Target kubernetes version. (default: 1.13.0)
#       local_data_root                 Path to store necessary data(binaries, configure, etc) during deployment. (default: /tmp/kubernetes-deploy)

- file:
    path: "{{ __local_kube_client_binary_root }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- include_vars: roles/kube_binaries/vars/binaries_url.yml
- include_tasks: roles/kube_binaries/tasks/client.yml
