---
- include_tasks: centos.yml
  when: inventory_hostname == 'localhost' or inventory_hostname == '127.0.0.1'
  delegate_to: localhost

- include_tasks: centos.yml
  when: inventory_hostname != 'localhost' and inventory_hostname != '127.0.0.1'
