---
- name: Ensure Shadowsocks config path exists.
  file:
      path: "{{ data_root }}"
      owner: root
      group: root
      mode: 0755
      state: directory

- name: Generate configure file
  template:
      src: config.json.j2
      dest: "{{ data_root }}/config.json"

- name: Generate docker-compose file
  template:
      src: docker-compose.yml.j2
      dest: "{{ data_root }}/docker-compose.yml"
  notify: start ss-local client
