#
#   @Description:
#       Generate an certificate signed by PKI CA.
#
#   @vars:
#       key_path        Private key path to save.
#       csr_path        CSR path to save.
#       crt_path        Certificate to save.
#       issuer:         Issuer information
#           CN: ...     CommonName
#           O:  ...     Organization
#
---
- stat:
      path: "{{ key_path }}"
  register: private_key

- name: Generate CA private key.
  openssl_privatekey:
      size: 4096
      path: "{{ key_path }}"
  when: private_key.stat.exists == False

- name: Generate CA CSR.
  openssl_csr:
      path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      common_name: "{{ issuer.CN }}"
      organization_name: "{{ issuer.O }}"

- name: Generate CA.
  openssl_certificate:
      issuer: "{{ issuer }}"
      path: "{{ crt_path }}"
      csr_path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      provider: selfsigned
