---
- stat:
      path: "{{ key_path }}"
  register: private_key

- name: Generate Certificate Private Key.
  openssl_privatekey:
      size: 4096
      path: "{{ key_path }}"
  when: private_key.stat.exists == False

- name: Generate Certificate CSR.
  openssl_csr:
      path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      common_name: "{{ issuer.CN }}"
      organization_name: "{{ issuer.O }}"

- name: Generate Certificate.
  openssl_certificate:
      issuer: "{{ issuer }}"
      path: "{{ crt_path }}"
      csr_path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      provider: ownca
      ownca_path: "{{ ca_path }}"
      ownca_privatekey_path: "{{ ca_key_path }}"
