#
#   @Description:
#       Generate an certificate signed by PKI CA.
#
#   @vars:
#       key_path        Private key path to save.
#       csr_path        CSR path to save.
#       crt_path        Certificate to save.
#       ca_path         CA certificate path.
#       ca_key_path     CA Private key.
#       issuer:         Issuer information
#           CN: ...     CommonName
#           O:  ...     Organization
#
---
- set_fact:
    __pki_root: "{{ pki_root | default(data_root + '/tls') }}"

- set_fact:
    __ca_path: "{{ ca_path | default( __pki_root + '/ca.crt') }}"
    __ca_key_path: "{{ ca_key_path | default( __pki_root + '/ca.key') }}"

- stat:
      path: "{{ key_path }}"
  register: private_key

- name: Generate Certificate Private Key.
  openssl_privatekey:
      size: 4096
      path: "{{ key_path }}"
  when: private_key.stat.exists == False

- name: Generate Certificate CSR.
  openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ key_path }}"
    common_name: "{{ issuer.CN }}"
    subject_alt_name: "{{ issuer.SAN | default(omit) }}"
    organization_name: "{{ issuer.O }}"

- name: Generate Certificate.
  openssl_certificate:
      issuer: "{{ issuer }}"
      path: "{{ crt_path }}"
      csr_path: "{{ csr_path }}"
      privatekey_path: "{{ key_path }}"
      provider: ownca
      ownca_path: "{{ __ca_path }}"
      ownca_privatekey_path: "{{ __ca_key_path }}"
