---
- set_fact:
    __pki_root: "{{ pki_root | default(data_root + '/tls') }}"
    
- name: Ensure PKI Root exists.
  file: 
    path: "{{ __pki_root }}"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Setup self-signed CA. 
  include_tasks: roles/certs/tasks/ca.yml
  vars:
      issuer:
          O: Starstudio APP Platform Authority
          CN: "*.starapp.com"
      crt_path: "{{ __pki_root }}/ca.crt"
      key_path: "{{ __pki_root }}/ca.key"
      csr_path: "{{ __pki_root }}/ca.csr"

