---
- set_fact:
    __local_data_root: "{{ local_data_root | default(playbook_dir + '/deploy_cluster_data') }}"

- set_fact:
    __local_pki_root: "{{ local_pki_root | default(__local_data_root + '/tls') }}"

- name: Ensure PKI Root exists.
  file: 
    path: "{{ __local_pki_root }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Setup self-signed CA. 
  include_tasks: roles/certs/tasks/ca.yml
  vars:
      issuer:
          O: Starstudio APP Platform Authority
          CN: "*.starapp.com"
      crt_path: "{{ __local_pki_root }}/ca.crt"
      key_path: "{{ __local_pki_root }}/ca.key"
      csr_path: "{{ __local_pki_root }}/ca.csr"

