#
#   Kubernetes binaries URL.
#
---

kubectl_bin_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ __kube_version }}/bin/linux/amd64/kubectl"
kubelet_bin_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ __kube_version }}/bin/linux/amd64/kubelet"
