#
#   Generate etcd cluster
#
#   @params:
#       local_data_root             Root to store cluster data. (default: {{ playbook_dir + '/deploy_cluster_data'}})
#       local_pki_root              Path to store cluster certificates (default: {{ local_data_root }}/tls)
#       local_etcd_cert_root        Path to store etcd certificates. (default: {{ local_pki_root }}/etcd)
#
---
- set_fact:
    __local_data_root: "{{ local_data_root | default(playbook_dir + '/deploy_cluster_data') }}"

- set_fact:
    __local_pki_root: "{{ local_pki_root | default(__local_data_root + '/tls') }}"

- set_fact:
    __local_etcd_cert_root: "{{ local_etcd_cert_root | default(__local_pki_root + '/etcd') }}"

- name: Ensure etcd certs root exists.
  file:
      path: "{{ __local_etcd_cert_root }}"
      owner: root
      group: root
      mode: 0644
      state: directory


- name: Ensure CA exists.
  include_tasks: roles/certs/tasks/main.yml
