---
- set_fact:
     cleandns_config_root: "{{ cleandns_data_root }}/config"
     cleandns_log_root: "{{ cleandns_data_root }}/log"
     listen_address: "{{ listen_address | default('127.0.0.1') }}"
     listen_port: "{{ listen_port | default('5353') }}"
     upstream_dns: "{{ upstream_dns | default('8.8.8.8') }}"
     upstream_port: "{{ upstream_port | default('53') }}"

      
- name: Ensure CleanDNS data path exists.
  file:
      path: "{{ data_root }}"
      owner: root
      group: root
      mode: 0755
      state: directory

- name: Ensure CleanDNS config path exists.
  file:
      path: "{{ cleandns_config_root }}"
      owner: root
      group: root
      mode: 0700
      state: directory

- name: Ensure CleanDNS log path exists.
  file:
      path: "{{ cleandns_log_root }}"
      owner: root
      group: root
      mode: 0700
      state: directory

- name: Preparing Docker Compose environment.
  include_tasks: build_image.yml
  
